[package]
name = "meilisearch-sdk"
version = "0.1.0"
authors = ["Mubelotix <mubelotix@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
minreq = "2.1"
serde_json = "1.0"
log = "0.4"
serde = {version="1.0", features=["derive"]}
urlencoding = "1.0"

[dev-dependencies]
env_logger = "0.7"