[package]
name = "meilisearch-sdk"
version = "0.1.0"
authors = ["Mubelotix <mubelotix@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
minreq = {path="../clones/minreq"}
serde_json = "1.0"
log = "0.4"
serde = {version="1.0", features=["derive"]}

[dev-dependencies]
env_logger = "0.7"

[patch.crates-io]
minreq = {git="https://github.com/neonmoe/minreq"}