[package]
name = "meilisearch-sdk"
version = "0.1.1"
authors = ["Mubelotix <mubelotix@gmail.com>"]
edition = "2018"
description = "MeiliSearch Rust SDK. MeiliSearch is a powerful, fast, open-source, easy to use and deploy search engine."
license = "MIT"
readme  = "README.md"

[dependencies]
serde_json = "1.0"
log = "0.4"
serde = {version="1.0", features=["derive"]}
urlencoding = "1.0"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
minreq = "2.1"

[target.'cfg(target_arch = "wasm32")'.dependencies]
web-sys = {version="0.3", features=["RequestInit", "Headers", "Window", "Response", "console"]}
wasm-bindgen = "0.2"

[dev-dependencies]
env_logger = "0.7"